### ISSUE TITLE
[FYI] Similar project

### ISSUE THREAD

**Issue by IOAyman** [BoFFire/xkb_dz#1]
FYI, there has been an Amazigh x11 layout done previously by @nlouahedj. 

https://github.com/nlouahedj/tamazight-layout

**Comment by BoFFire** [comment]
Hello @IOAyman :)
Yep I know, similar but not the same project.
The aim of my project is to standardise based on Unicode by creating a variant without éèàù'çÇÀ and so on introduced by french azerty.
Please check the code which is work in progress.
Cc @nlouahedj I saw your work :)

**Comment by IOAyman** [comment]
Sure. I'll keep an eye on the project once in a while.

Best of wishes!
